openapi: 3.2.0
info:
  title: REST API for Oracle Eloqua Marketing Cloud Service Application/1.0/Contact list API
  description: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
  version: 2026.08.07
  x-summary: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
tags:
- name: Application/1.0/Contact list
  description: Customized lists of contacts.
paths:
  /api/rest/1.0/assets/contact/list:
    post:
      operationId: CreateIndividualPOSTRest10
      summary: Create a contact list
      description: Creates a contact list that matches the criteria specified by the request body.
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactListRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contact list
      x-internal-id: api-rest-1.0-assets-contact-list-post
      x-filename-id: api-rest-1.0-assets-contact-list-post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactListRest10'
        description: The request body defines the details of the contact list to be created.
        required: true
  /api/rest/1.0/assets/contact/list/{id}:
    get:
      operationId: ReadIndividualGETRest10
      parameters:
      - name: id
        in: path
        description: Id of the contact list.
        required: true
        schema:
          type: integer
      - name: depth
        in: query
        description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>complete</code> by default. For more information, see <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=RequestDepth''>Request depth</a>.'
        required: false
        schema:
          type: string
      summary: Retrieve a contact list
      description: Retrieves the contact list specified by the <code>id</code> parameter.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactListRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contact list
      x-internal-id: api-rest-1.0-assets-contact-list-{id}-get
      x-filename-id: api-rest-1.0-assets-contact-list-id-get
    put:
      operationId: UpdateIndividualPUTRest10
      parameters:
      - name: id
        in: path
        description: Id of the contact list.
        required: true
        schema:
          type: integer
      summary: Update a contact list
      description: Updates the contact list specified by the <code>id</code> parameter. All properties should be included in PUT requests, as some properties will be considered blank if not included.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactListRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contact list
      x-internal-id: api-rest-1.0-assets-contact-list-{id}-put
      x-filename-id: api-rest-1.0-assets-contact-list-id-put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactListRest10'
        description: The request body defines the details of the contact list to be updated.
        required: true
    delete:
      operationId: DeleteIndividualDELETERest10
      parameters:
      - name: id
        in: path
        description: Id of the contact list.
        required: true
        schema:
          type: integer
      summary: Delete a contact list
      description: Deletes the contact list specified by the <code>id</code> parameter.
      responses:
        '200':
          description: OK
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contact list
      x-internal-id: api-rest-1.0-assets-contact-list-{id}-delete
      x-filename-id: api-rest-1.0-assets-contact-list-id-delete
  /api/rest/1.0/assets/contact/lists:
    get:
      operationId: SearchGETRest10
      parameters:
      - name: depth
        in: query
        description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>minimal</code> by default.'
        required: false
        schema:
          type: string
      - name: count
        in: query
        description: Maximum number of entities to return. Must be less than or equal to 1000 and greater than or equal to 1.
        required: false
        schema:
          type: integer
      - name: page
        in: query
        description: Specifies which page of entities to return (the count parameter defines the number of entities per page). If the page parameter is not supplied, 1 will be used by default.
        required: false
        schema:
          type: integer
      - name: search
        in: query
        description: Specifies the search criteria used to retrieve entities. See the <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=SearchParam'>tutorial</a> for information about using this parameter.
        required: false
        schema:
          type: string
      - name: orderBy
        in: query
        description: Specifies the field by which list results are ordered.
        required: false
        schema:
          type: string
      - name: lastUpdatedAt
        in: query
        description: Unix timestamp for the date and time the contact list was last updated.
        required: false
        schema:
          type: integer
      summary: Retrieve a list of contact lists
      description: Retrieves all contact lists that match the criteria specified by the request parameters.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResultListRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contact list
      x-internal-id: api-rest-1.0-assets-contact-lists-get
      x-filename-id: api-rest-1.0-assets-contact-lists-get
components:
  schemas:
    QueryResultListRest10:
      title: QueryResultList
      properties:
        type:
          type: string
          description: The asset's type in Eloqua.
        elements:
          type: array
          description: Array of contact list fields.
          items:
            $ref: '#/components/schemas/ContactListRest10'
        total:
          type: integer
          description: The total amount of results.
        pageSize:
          type: integer
          description: The page size.
        page:
          type: integer
          description: The specified page.
    ContactListRest10:
      title: ContactList
      properties:
        type:
          type: string
          description: 'The asset''s type in Eloqua. This is a read-only property. '
        id:
          type: string
          readOnly: true
          description: Id of the contact list.
        currentStatus:
          type: string
          description: The contact list's current status. This is a read-only property.
        name:
          type: string
          description: The contact list's name.
        description:
          type: string
          description: The description of the contact list.
        permissions:
          type: string
          description: The permissions for the contact list granted to your current instance. This is a read-only property.
        createdBy:
          type: string
          readOnly: true
          description: The login id of the user who created the contact list. This is a read-only property.
        createdAt:
          type: string
          readOnly: true
          description: The date and time the contact segment was created, expressed in Unix time.
        updatedBy:
          type: string
          readOnly: true
          description: The login id of the user that last updated the contact list.
        updatedAt:
          type: string
          readOnly: true
          description: Unix timestamp for the date and time the contact list was last updated.
        depth:
          type: string
          readOnly: true
          description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>complete</code> by default. For more information, see <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=RequestDepth''>Request depth</a>.'
        scope:
          type: string
          description: 'The contact list''s scope: either <code>local</code> or <code>global</code>.'
        count:
          type: string
          readOnly: true
          description: The number of contacts in the contact list. This is a read-only property.
        membershipAdditions:
          type: array
          description: The number of contact membership additions in the contact list.
          items:
            type: string
        membershipDeletions:
          type: array
          description: The number of contact membership deletions in the contact list.
          items:
            type: string
        dataLookupId:
          type: string
          description: The contact list's data lookup Id. This is a read-only property.
