openapi: 3.2.0
info:
  title: REST API for Oracle Eloqua Marketing Cloud Service Application/1.0/Contacts API
  description: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
  version: 2026.08.07
  x-summary: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
tags:
- name: Application/1.0/Contacts
  description: 'A contact is a data entity that contains the explicit data around an individual person in the database.


    <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAA/index.html#CSHID=Contacts''>Learn more about contacts</a>.'
paths:
  /api/rest/1.0/data/contact:
    post:
      operationId: CreateIndividualPOSTRest10
      summary: Create a contact
      description: Creates a contact that matches the criteria specified by the request body
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contacts
      x-internal-id: api-rest-1.0-data-contact-post
      x-filename-id: api-rest-1.0-data-contact-post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRest10'
        description: The request body defines the details of the contact to be created.
        required: true
  /api/rest/1.0/data/contact/{id}:
    get:
      operationId: ReadIndividualGETRest10
      parameters:
      - name: id
        in: path
        description: Id of the contact.
        required: true
        schema:
          type: integer
      - name: depth
        in: query
        description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>complete</code> by default. For more information, see <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=RequestDepth''>Request depth</a>.'
        required: false
        schema:
          type: string
      - name: viewId
        in: query
        description: Id of the contact view.
        required: false
        schema:
          type: integer
      summary: Retrieve a contact
      description: Retrieves the contact specified by the <code>id</code> parameter.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contacts
      x-internal-id: api-rest-1.0-data-contact-{id}-get
      x-filename-id: api-rest-1.0-data-contact-id-get
    put:
      operationId: UpdateIndividualPUTRest10
      parameters:
      - name: id
        in: path
        description: Id of the contact.
        required: true
        schema:
          type: integer
      summary: Update a contact
      description: Updates the contact specified by the <code>id</code> parameter. All properties should be included in PUT requests, as some properties will be considered blank if not included.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contacts
      x-internal-id: api-rest-1.0-data-contact-{id}-put
      x-filename-id: api-rest-1.0-data-contact-id-put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRest10'
        description: The request body defines the details of the contact to be updated.
        required: true
    delete:
      operationId: DeleteIndividualDELETERest10
      parameters:
      - name: id
        in: path
        description: Id of the contact
        required: true
        schema:
          type: integer
      summary: Delete a contact
      description: Deletes a contact specified by the <code>id</code> parameter
      responses:
        '204':
          description: No matching contacts were found in the search
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '409':
          description: The contact you are attempting to delete has dependencies, and cannot be deleted
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contacts
      x-internal-id: api-rest-1.0-data-contact-{id}-delete
      x-filename-id: api-rest-1.0-data-contact-id-delete
  /api/rest/1.0/data/contacts:
    get:
      operationId: SearchGETRest10
      parameters:
      - name: depth
        in: query
        description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>minimal</code> by default.'
        required: false
        schema:
          type: string
      - name: count
        in: query
        description: Maximum number of entities to return. Must be less than or equal to 1000 and greater than or equal to 1.
        required: false
        schema:
          type: integer
      - name: page
        in: query
        description: Specifies which page of entities to return (the count parameter defines the number of entities per page). If the page parameter is not supplied, 1 will be used by default.
        required: false
        schema:
          type: integer
      - name: search
        in: query
        description: Specifies the search criteria used to retrieve entities. See the <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=SearchParam'>tutorial</a> for information about using this parameter.
        required: false
        schema:
          type: string
      - name: orderBy
        in: query
        description: Specifies the field by which list results are ordered.
        required: false
        schema:
          type: string
      - name: lastUpdatedAt
        in: query
        description: Unix timestamp for the date and time the contact was last updated. This is a read-only property.
        required: false
        schema:
          type: integer
      - name: viewId
        in: query
        description: 'Id of the contact view to filter results. Must be a valid contact view id. Example: <code>?viewId=100006</code>.'
        required: false
        schema:
          type: integer
      summary: Retrieve a list of contacts
      description: Retrieves all contacts that match the criteria specified by the request parameters
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResultContactRest10'
        '204':
          description: No matching contacts were found in the search
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Contacts
      x-internal-id: api-rest-1.0-data-contacts-get
      x-filename-id: api-rest-1.0-data-contacts-get
components:
  schemas:
    ContactRest10:
      title: Contact
      properties:
        type:
          type: string
          description: 'The asset''s type in Eloqua. This is a read-only property. '
        id:
          type: string
          readOnly: true
          description: Id of the contact. This is a read-only property.
        currentStatus:
          type: string
          description: The contact's current status.
        name:
          type: string
          description: The name of the contact.
        description:
          type: string
          description: The description of the contact.
        permissions:
          type: string
          description: The permissions for the contact granted to your current instance. This is a read-only property.
        createdBy:
          type: string
          readOnly: true
          description: The login id of the user who created the contact.
        createdAt:
          type: string
          readOnly: true
          description: The date and time the contact was created, expressed in Unix time.
        updatedBy:
          type: string
          readOnly: true
          description: The login id of the user that last updated the contact.
        updatedAt:
          type: string
          readOnly: true
          description: Unix timestamp for the date and time the contact was last updated.
        depth:
          type: string
          readOnly: true
          description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>complete</code> by default. For more information, see <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=RequestDepth''>Request depth</a>.'
        firstName:
          type: string
          description: The contact's first name.
        lastName:
          type: string
          description: The contact's last name.
        emailAddress:
          type: string
          description: The contact's email address.
        emailFormatPreference:
          type: string
          description: The contact's email format preference.
        isSubscribed:
          type: string
          description: Whether or not the contact is subscribed.
        isBounceback:
          type: string
          description: Whether or not the contact has any associated bouncebacks.
        accountName:
          type: string
          description: The account name in which the contact belongs.
        accountId:
          type: string
          description: The account id in which the contact belongs. This is a read-only property.
        title:
          type: string
          description: The contact's title.
        subscriptionDate:
          type: string
          description: The contact's subscription date.
        unsubscriptionDate:
          type: string
          description: The contact's unsubscription date.
        bouncebackDate:
          type: string
          description: The contact's bounceback date.
        fieldValues:
          type: array
          description: Array containing <code>type</code> and <code>id</code> values for all of the contactFields associated with a given contact.
          items:
            $ref: '#/components/schemas/FieldValueRest10'
        address1:
          type: string
          description: The contact's first address.
        address2:
          type: string
          description: The contact's second address.
        address3:
          type: string
          description: The contact's third address.
        city:
          type: string
          description: The contact's city.
        province:
          type: string
          description: The contact's province.
        postalCode:
          type: string
          description: The contact's postal code.
        country:
          type: string
          description: The contact's country.
        businessPhone:
          type: string
          description: The contact's business phone number.
        mobilePhone:
          type: string
          description: The contact's mobile phone number.
        fax:
          type: string
          description: The contact's fax number.
        salesPerson:
          type: string
          description: The contact's account representative.
    QueryResultContactRest10:
      title: QueryResultContact
      properties:
        type:
          type: string
          description: The asset's type in Eloqua.
        elements:
          type: array
          description: Array of contact fields.
          items:
            $ref: '#/components/schemas/ContactRest10'
        total:
          type: integer
          description: The total amount of results.
        pageSize:
          type: integer
          description: The page size.
        page:
          type: integer
          description: The specified page.
    FieldValueRest10:
      title: FieldValue
      properties:
        type:
          type: string
          description: The asset's type in Eloqua. This is a read-only property.
        value:
          type: string
          description: The value to set the corresponding field id to. Date values must be submitted as a unix timestamp.
        id:
          type: string
          readOnly: true
          description: The id of the field to be set to the corresponding value.
