openapi: 3.2.0
info:
  title: REST API for Oracle Eloqua Marketing Cloud Service Reporting/Campaign Analysis/1.0/External Activity Totals API
  description: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
  version: 2026.08.07
  x-summary: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
tags:
- name: Reporting/CampaignAnalysis/1.0/ExternalActivityTotals
  description: The operations from the Reporting/CampaignAnalysis/1.0/ExternalActivityTotals category.
paths:
  /API/OData/CampaignAnalysis/1/ExternalActivityTotals:
    get:
      tags:
      - Reporting/CampaignAnalysis/1.0/ExternalActivityTotals
      summary: Get all External Activity Totals.
      operationId: ExternalActivityTotals_Get
      parameters:
      - name: $select
        in: query
        description: Limits the properties returned in the result.
        required: false
        schema:
          type: string
      - name: $expand
        in: query
        description: Indicates the related entities to be represented inline. The maximum depth is 2.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: 'Restricts the set of items returned. The maximum number of expressions is 100. The allowed functions are: allfunctions.'
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Specifies the order in which items are returned. The maximum number of expressions is 5.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Limits the number of items returned from a collection. The maximum value is 20000.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Excludes the specified number of items of the queried collection from the result.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Indicates whether the total count of items within a collection are returned in the result.
        required: false
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: ExternalActivityTotals successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExternalActivityTotals'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExternalActivityTotals'
      x-internal-id: API-OData-CampaignAnalysis-1-ExternalActivityTotals-get
      x-filename-id: api-odata-campaignanalysis-1-externalactivitytotals-get
components:
  schemas:
    ExternalActivityTotals:
      type: object
      properties:
        externalAssetId:
          format: int32
          type: integer
        externalAssetType:
          format: int32
          type: integer
        eloquaCampaignId:
          format: int32
          type: integer
        totalExternalActivities:
          format: int32
          type: integer
        dateHour:
          format: date-time
          type: string
        lastModifiedDate:
          format: date-time
          type: string
        campaign:
          $ref: '#/components/schemas/Campaign'
    Campaign:
      type: object
      properties:
        eloquaCampaignId:
          format: int32
          type: integer
        campaignName:
          type: string
        crmCampaignId:
          type: string
        campaignDescription:
          type: string
        campaignCreatedDateTime:
          format: date-time
          type: string
        campaignProduct:
          type: string
        campaignRegion:
          type: string
        campaignType:
          type: string
        campaignStatus:
          type: string
        isDeleted:
          type: boolean
        campaignStartDate:
          format: date-time
          type: string
        campaignEndDate:
          format: date-time
          type: string
        campaignCreatedByUserId:
          format: int32
          type: integer
        lastActivatedByUserId:
          format: int32
          type: integer
        lastModifiedDate:
          format: date-time
          type: string
        campaignClassification:
          type: string
        adCampaignId:
          type: string
        referenceProduct:
          type: string
        actualCost:
          format: double
          type: number
        budgetedCost:
          format: double
          type: number
