openapi: 3.2.0
info:
  title: REST API for Oracle Eloqua Marketing Cloud Service Reporting/Campaign Analysis/1.0/Form Activities API
  description: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
  version: 2026.08.07
  x-summary: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
tags:
- name: Reporting/CampaignAnalysis/1.0/FormActivities
  description: The operations from the Reporting/CampaignAnalysis/1.0/FormActivities category.
paths:
  /API/OData/CampaignAnalysis/1/FormActivities:
    get:
      tags:
      - Reporting/CampaignAnalysis/1.0/FormActivities
      summary: Get all Form Activities
      operationId: FormActivities_Get
      parameters:
      - name: $select
        in: query
        description: Limits the properties returned in the result.
        required: false
        schema:
          type: string
      - name: $expand
        in: query
        description: Indicates the related entities to be represented inline. The maximum depth is 2.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: 'Restricts the set of items returned. The maximum number of expressions is 100. The allowed functions are: allfunctions.'
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Specifies the order in which items are returned. The maximum number of expressions is 5.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Limits the number of items returned from a collection. The maximum value is 20000.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Excludes the specified number of items of the queried collection from the result.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Indicates whether the total count of items within a collection are returned in the result.
        required: false
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: FormActivities successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormActivities'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormActivities'
      x-internal-id: API-OData-CampaignAnalysis-1-FormActivities-get
      x-filename-id: api-odata-campaignanalysis-1-formactivities-get
  /API/OData/CampaignAnalysis/1/FormActivities/{key}:
    get:
      tags:
      - Reporting/CampaignAnalysis/1.0/FormActivities
      summary: Get a single Form Activities
      operationId: FormActivitiest_Get_By_ID
      parameters:
      - name: key
        in: path
        description: FormActivitiesID
        required: true
        schema:
          type: integer
          format: int32
      - name: $select
        in: query
        description: Limits the properties returned in the result.
        required: false
        schema:
          type: string
      - name: $expand
        in: query
        description: Indicates the related entities to be represented inline. The maximum depth is 2.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: 'Restricts the set of items returned. The maximum number of expressions is 100. The allowed functions are: allfunctions.'
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Specifies the order in which items are returned. The maximum number of expressions is 5.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Limits the number of items returned from a collection. The maximum value is 20000.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Excludes the specified number of items of the queried collection from the result.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Indicates whether the total count of items within a collection are returned in the result.
        required: false
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: FormActivities was successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormActivities'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormActivities'
      x-internal-id: API-OData-CampaignAnalysis-1-FormActivities-{key}-get
      x-filename-id: api-odata-campaignanalysis-1-formactivities-key-get
components:
  schemas:
    Calendar:
      type: object
      properties:
        dateHour:
          format: date-time
          type: string
        calendarYear:
          format: int32
          type: integer
        calendarYearDesc:
          type: string
        calendarQtr:
          format: int32
          type: integer
        calendarQtrDesc:
          type: string
        calendarMonth:
          format: int32
          type: integer
        calendarMonthDesc:
          type: string
        calendarWeek:
          format: int32
          type: integer
        calendarWeekDesc:
          type: string
        dayOfYearNum:
          format: int32
          type: integer
        dayOfWeekNum:
          format: int32
          type: integer
        dayOfWeekDesc:
          type: string
        dayOfMonthNum:
          format: int32
          type: integer
        displayDayOfWeek:
          type: string
        hourOfDayNum:
          format: int32
          type: integer
        calendarMonthId:
          format: int32
          type: integer
        calendarQtrId:
          format: int32
          type: integer
        calendarWeekId:
          format: int32
          type: integer
        calendarDayId:
          format: date-time
          type: string
    Campaign:
      type: object
      properties:
        eloquaCampaignId:
          format: int32
          type: integer
        campaignName:
          type: string
        crmCampaignId:
          type: string
        campaignDescription:
          type: string
        campaignCreatedDateTime:
          format: date-time
          type: string
        campaignProduct:
          type: string
        campaignRegion:
          type: string
        campaignType:
          type: string
        campaignStatus:
          type: string
        isDeleted:
          type: boolean
        campaignStartDate:
          format: date-time
          type: string
        campaignEndDate:
          format: date-time
          type: string
        campaignCreatedByUserId:
          format: int32
          type: integer
        lastActivatedByUserId:
          format: int32
          type: integer
        lastModifiedDate:
          format: date-time
          type: string
        campaignClassification:
          type: string
        adCampaignId:
          type: string
        referenceProduct:
          type: string
        actualCost:
          format: double
          type: number
        budgetedCost:
          format: double
          type: number
    FormActivities:
      type: object
      properties:
        formSubmitAggKey:
          format: int32
          type: integer
        totalFormSubmissions:
          format: int32
          type: integer
        eloquaCampaignID:
          format: int32
          type: integer
        segmentId:
          format: int32
          type: integer
        dateHour:
          format: date-time
          type: string
        lastModifiedDate:
          format: date-time
          type: string
        campaign:
          $ref: '#/components/schemas/Campaign'
        calendar:
          $ref: '#/components/schemas/Calendar'
        segment:
          $ref: '#/components/schemas/Segment'
    Segment:
      type: object
      properties:
        segmentId:
          format: int32
          type: integer
        segment:
          type: string
        segmentDescription:
          type: string
        segmentCreatedByUserId:
          format: int32
          type: integer
        lastModifiedDate:
          format: date-time
          type: string
