openapi: 3.2.0
info:
  title: REST API for Oracle Eloqua Marketing Cloud Service Reporting/Landing Page Analysis/1.0/Landing Page Activity API
  description: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
  version: 2026.08.07
  x-summary: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
tags:
- name: Reporting/LandingPageAnalysis/1.0/LandingPageActivity
  description: The operations from the Reporting/LandingPageAnalysis/1.0/LandingPageActivity category.
paths:
  /API/OData/LandingPageAnalysis/1/LandingPageActivity:
    get:
      tags:
      - Reporting/LandingPageAnalysis/1.0/LandingPageActivity
      summary: Get all Landing Page Activities
      operationId: LandingPageActivity_Get
      parameters:
      - name: $select
        in: query
        description: Limits the properties returned in the result.
        required: false
        schema:
          type: string
      - name: $expand
        in: query
        description: Indicates the related entities to be represented inline. The maximum depth is 2.
        required: false
        schema:
          type: string
      - name: $filter
        in: query
        description: 'Restricts the set of items returned. The maximum number of expressions is 100. The allowed functions are: allfunctions.'
        required: false
        schema:
          type: string
      - name: $orderby
        in: query
        description: Specifies the order in which items are returned. The maximum number of expressions is 5.
        required: false
        schema:
          type: string
      - name: $top
        in: query
        description: Limits the number of items returned from a collection. The maximum value is 20000.
        required: false
        schema:
          type: integer
          format: int32
      - name: $skip
        in: query
        description: Excludes the specified number of items of the queried collection from the result.
        required: false
        schema:
          type: integer
          format: int32
      - name: $count
        in: query
        description: Indicates whether the total count of items within a collection are returned in the result.
        required: false
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: LandingPageActivity successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LandingPageActivity'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LandingPageActivity'
      x-internal-id: API-OData-LandingPageAnalysis-1-LandingPageActivity-get
      x-filename-id: api-odata-landingpageanalysis-1-landingpageactivity-get
components:
  schemas:
    Calendar:
      type: object
      properties:
        dateHour:
          format: date-time
          type: string
        calendarYear:
          format: int32
          type: integer
        calendarYearDesc:
          type: string
        calendarQtr:
          format: int32
          type: integer
        calendarQtrDesc:
          type: string
        calendarMonth:
          format: int32
          type: integer
        calendarMonthDesc:
          type: string
        calendarWeek:
          format: int32
          type: integer
        calendarWeekDesc:
          type: string
        dayOfYearNum:
          format: int32
          type: integer
        dayOfWeekNum:
          format: int32
          type: integer
        dayOfWeekDesc:
          type: string
        dayOfMonthNum:
          format: int32
          type: integer
        displayDayOfWeek:
          type: string
        hourOfDayNum:
          format: int32
          type: integer
        calendarMonthId:
          format: int32
          type: integer
        calendarQtrId:
          format: int32
          type: integer
        calendarWeekId:
          format: int32
          type: integer
        calendarDayId:
          format: date-time
          type: string
    LandingPageActivity:
      type: object
      properties:
        averageLandingPageTime:
          format: double
          type: number
          readOnly: true
        eloquaCampaignID:
          format: int32
          type: integer
        landingPageID:
          format: int32
          type: integer
        landingPageTime:
          format: double
          type: number
        landingPageViews:
          format: int32
          type: integer
        webClickDateHour:
          format: date-time
          type: string
        totalVisitors:
          format: int32
          type: integer
        totalVisits:
          format: int32
          type: integer
        calendar:
          $ref: '#/components/schemas/Calendar'
