openapi: 3.2.0
info:
  title: REST API for Oracle Eloqua Marketing Cloud Service Application/2.0/SMS invalid keyword messages API
  description: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
  version: 2026.08.07
  x-summary: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
tags:
- name: Application/2.0/SMS invalid keyword messages
  description: SMS invalid keyword response message API endpoints.
paths:
  /api/rest/2.0/assets/sms/invalidResponseMessages:
    get:
      operationId: SearchGETRest20
      parameters:
      - name: depth
        in: query
        description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>minimal</code> by default.'
        required: false
        schema:
          type: string
      - name: count
        in: query
        description: Maximum number of entities to return. Must be less than or equal to 1000 and greater than or equal to 1.
        required: false
        schema:
          type: integer
      - name: page
        in: query
        description: Specifies which page of entities to return (the count parameter defines the number of entities per page). If the page parameter is not supplied, 1 will be used by default.
        required: false
        schema:
          type: integer
      - name: search
        in: query
        description: Specifies the search criteria used to retrieve entities. See the <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=SearchParam'>tutorial</a> for information about using this parameter.
        required: false
        schema:
          type: string
      - name: orderBy
        in: query
        description: Specifies the field by which list results are ordered.
        required: false
        schema:
          type: string
      - name: lastUpdatedAt
        in: query
        description: The date and time the message was last updated.
        required: false
        schema:
          type: integer
      summary: Retrieve a list of message
      description: Retrieves all message that match the criteria specified by the request parameters.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResultInvalidResponseMessageRest20'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/2.0/SMS invalid keyword messages
      x-internal-id: api-rest-2.0-assets-sms-invalidResponseMessages-get
      x-filename-id: api-rest-2.0-assets-sms-invalidresponsemessages-get
  /api/rest/2.0/assets/sms/invalidResponseMessage/{id}:
    get:
      operationId: ReadIndividualGETRest20
      parameters:
      - name: id
        in: path
        description: Id of the message
        required: true
        schema:
          type: integer
      - name: depth
        in: query
        description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>minimal</code> by default.'
        required: false
        schema:
          type: string
      summary: Retrieve a message
      description: Retrieves the message specified by the <code>id</code> parameter.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidResponseMessageRest20'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/2.0/SMS invalid keyword messages
      x-internal-id: api-rest-2.0-assets-sms-invalidResponseMessage-{id}-get
      x-filename-id: api-rest-2.0-assets-sms-invalidresponsemessage-id-get
    put:
      operationId: UpdateIndividualPUTRest20
      parameters:
      - name: id
        in: path
        description: Id of the message
        required: true
        schema:
          type: string
      summary: Update a message
      description: The request body defines the details of the message to be updated.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidResponseMessageRest20'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/2.0/SMS invalid keyword messages
      x-internal-id: api-rest-2.0-assets-sms-invalidResponseMessage-{id}-put
      x-filename-id: api-rest-2.0-assets-sms-invalidresponsemessage-id-put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvalidResponseMessageRest20'
        description: The request body defines the details of the message to be updated.
        required: true
    delete:
      operationId: DeleteIndividualDELETERest20
      parameters:
      - name: id
        in: path
        description: Id of the message
        required: true
        schema:
          type: integer
      summary: Delete a message
      description: Deletes the message specified by the <code>id</code> parameter.
      responses:
        '200':
          description: OK
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/2.0/SMS invalid keyword messages
      x-internal-id: api-rest-2.0-assets-sms-invalidResponseMessage-{id}-delete
      x-filename-id: api-rest-2.0-assets-sms-invalidresponsemessage-id-delete
  /api/rest/2.0/assets/sms/invalidResponseMessage:
    post:
      operationId: CreateIndividualPOSTRest20
      summary: Create a message
      description: Creates a message that matches the criteria specified by the request body.
      responses:
        '201':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidResponseMessageRest20'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/2.0/SMS invalid keyword messages
      x-internal-id: api-rest-2.0-assets-sms-invalidResponseMessage-post
      x-filename-id: api-rest-2.0-assets-sms-invalidresponsemessage-post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvalidResponseMessageRest20'
        description: The request body defines the details of the message to be created.
        required: true
components:
  schemas:
    QueryResultInvalidResponseMessageRest20:
      title: QueryResultInvalidResponseMessage
      properties:
        type:
          type: string
          description: The asset's type in Eloqua.
        elements:
          type: array
          description: Array of invalid response message fields.
          items:
            $ref: '#/components/schemas/InvalidResponseMessageRest20'
        total:
          type: integer
          description: The total amount of results.
        pageSize:
          type: integer
          description: The page size.
        page:
          type: integer
          description: The specified page.
    InvalidResponseMessageRest20:
      title: InvalidResponseMessage
      properties:
        type:
          type: string
          description: The asset's type in Eloqua. This is a read-only property.
        id:
          type: string
          readOnly: true
          description: Id of the invalid response message. This is a read-only property.
        currentStatus:
          type: string
          description: The invalid response message's current status. This is a read-only property.
        description:
          type: string
          description: The description of the invalid response message.
        permissions:
          type: array
          description: The permissions for the invalid response message granted to your current instance. This is a read-only property.
          items:
            type: string
        folderId:
          type: string
          readOnly: true
          description: The folder id of the folder which contains the invalid response message.
        sourceTemplateId:
          type: string
          description: Id of the template used to create the invalid response message.
        createdBy:
          type: string
          readOnly: true
          description: The login id of the user who created the invalid response message.
        createdByName:
          type: string
          description: The name of the user who created the invalid response message.
        createdAt:
          type: string
          readOnly: true
          description: The date and time the invalid response message was created, expressed in Unix time.
        updatedBy:
          type: string
          readOnly: true
          description: The login id of the user that last updated the invalid response message.
        updatedByName:
          type: string
          description: The name of the user who last updated the invalid response message.
        updatedAt:
          type: string
          readOnly: true
          description: Unix timestamp for the date and time the invalid response code was last updated.
        scheduledFor:
          type: string
          readOnly: true
          description: This property is not used.
        depth:
          type: string
          readOnly: true
          description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>complete</code> by default. For more information, see <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=RequestDepth''>Request depth</a>.'
        response:
          type: string
          description: The invalid response message
        templateId:
          type: string
          description: This property is not used.
        senderCodeId:
          type: integer
          description: Id of the associated sender code.
        countryCodes:
          type: array
          description: Country codes associated with invalid response message.
          items:
            type: string
