openapi: 3.2.0
info:
  title: REST API for Oracle Eloqua Marketing Cloud Service Application/1.0/Custom objects API
  description: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
  version: 2026.08.07
  x-summary: The Oracle Eloqua Marketing Cloud Service REST APIs enable you to extend the functionality of the product, build Apps, and perform high volume data transfers.
tags:
- name: Application/1.0/Custom objects
  description: 'Custom objects are a complement to the standard Data Entities (i.e. Contacts, Companies). Essentially, custom objects are used for two main functions: linking directly to a Contact and performing actions based on information collected without duplication.


    <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAA/index.html#CSHID=CustomObjects''>Learn more about custom objects</a>.'
paths:
  /api/rest/1.0/assets/customObject:
    post:
      operationId: CreateIndividualPOSTRest10
      summary: Create a custom object
      description: Creates a custom object that matches the criteria specified by the request body.
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomObjectRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Custom objects
      x-internal-id: api-rest-1.0-assets-customObject-post
      x-filename-id: api-rest-1.0-assets-customobject-post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomObjectRest10'
        description: The request body defines the details of the custom object to be created.
        required: true
  /api/rest/1.0/assets/customObject/{id}:
    get:
      operationId: ReadIndividualGETRest10
      parameters:
      - name: id
        in: path
        description: Id of the custom object.
        required: true
        schema:
          type: integer
      - name: depth
        in: query
        description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>complete</code> by default. For more information, see <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=RequestDepth''>Request depth</a>.'
        required: false
        schema:
          type: string
      summary: Retrieve a custom object
      description: Retrieves the custom object specified by the <code>id</code> parameter.
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomObjectRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Custom objects
      x-internal-id: api-rest-1.0-assets-customObject-{id}-get
      x-filename-id: api-rest-1.0-assets-customobject-id-get
    put:
      operationId: UpdateIndividualPUTRest10
      parameters:
      - name: id
        in: path
        description: Id of the custom object.
        required: true
        schema:
          type: integer
      summary: Update a custom object
      description: Updates the custom object specified by the <code>id</code> parameter. All properties should be included in PUT requests, as some properties will be considered blank if not included.
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomObjectRest10'
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Custom objects
      x-internal-id: api-rest-1.0-assets-customObject-{id}-put
      x-filename-id: api-rest-1.0-assets-customobject-id-put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomObjectRest10'
        description: The request body defines the details of the custom object to be updated.
        required: true
    delete:
      operationId: DeleteIndividualDELETERest10
      parameters:
      - name: id
        in: path
        description: Id of the custom object.
        required: true
        schema:
          type: integer
      summary: Delete a custom object
      description: Deletes the custom object  specified by the <code>id</code> parameter.
      responses:
        '204':
          description: No matching custom objects were found in the search.
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '409':
          description: The custom object you are attempting to delete has dependencies, and cannot be deleted.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Custom objects
      x-internal-id: api-rest-1.0-assets-customObject-{id}-delete
      x-filename-id: api-rest-1.0-assets-customobject-id-delete
  /api/rest/1.0/assets/customObjects:
    get:
      operationId: SearchGETRest10
      parameters:
      - name: depth
        in: query
        description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>minimal</code> by default.'
        required: false
        schema:
          type: string
      - name: count
        in: query
        description: Maximum number of entities to return. Must be less than or equal to 1000 and greater than or equal to 1.
        required: false
        schema:
          type: integer
      - name: page
        in: query
        description: Specifies which page of entities to return (the count parameter defines the number of entities per page). If the page parameter is not supplied, 1 will be used by default.
        required: false
        schema:
          type: integer
      - name: search
        in: query
        description: Specifies the search criteria used to retrieve entities. See the <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=SearchParam'>tutorial</a> for information about using this parameter.
        required: false
        schema:
          type: string
      - name: orderBy
        in: query
        description: Specifies the field by which list results are ordered.
        required: false
        schema:
          type: string
      - name: lastUpdatedAt
        in: query
        description: The date and time the custom object was last updated.
        required: false
        schema:
          type: integer
      summary: Retrieve a list of custom objects
      description: Retrieves all custom objects that match the criteria specified by the request parameters.
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResultCustomObjectRest10'
        '204':
          description: No matching custom objects were found in the search.
        '400':
          description: Bad request. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '401':
          description: Unauthorized. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '403':
          description: Forbidden. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '404':
          description: The requested resource was not found. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
        '500':
          description: The service has encountered an error. See <a href='https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=HTTPStatusCodes'>Status Codes</a> for information about other possible HTTP status codes.
      tags:
      - Application/1.0/Custom objects
      x-internal-id: api-rest-1.0-assets-customObjects-get
      x-filename-id: api-rest-1.0-assets-customobjects-get
components:
  schemas:
    QueryResultCustomObjectRest10:
      title: QueryResultCustomObject
      properties:
        type:
          type: string
          description: The asset's type in Eloqua.
        elements:
          type: array
          description: Array of custom object fields.
          items:
            $ref: '#/components/schemas/CustomObjectRest10'
        total:
          type: integer
          description: The total amount of results.
        pageSize:
          type: integer
          description: The page size.
        page:
          type: integer
          description: The specified page.
    CustomObjectRest10:
      title: CustomObject
      properties:
        type:
          type: string
          description: The asset's type in Eloqua. This is a read-only property.
        id:
          type: string
          readOnly: true
          description: Id of the custom object.
        currentStatus:
          type: string
          description: This property is not used for custom object fields.
        name:
          type: string
          description: The name of the custom object.
        description:
          type: string
          description: The description of the custom object.
        permissions:
          type: string
          description: The permissions for the custom object granted to your current instance. This is a read-only property.
        createdBy:
          type: string
          readOnly: true
          description: The login id of the user who created the custom object.
        createdAt:
          type: string
          readOnly: true
          description: The date and time the custom object was created, expressed in Unix time.
        updatedBy:
          type: string
          readOnly: true
          description: The login id of the user that last updated the custom object.
        updatedAt:
          type: string
          readOnly: true
          description: Unix timestamp for the date and time the custom object was last updated.
        depth:
          type: string
          readOnly: true
          description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>complete</code> by default. For more information, see <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=RequestDepth''>Request depth</a>.'
        fields:
          type: array
          description: Array consisting of custom object field properties.
          items:
            $ref: '#/components/schemas/CustomObjectFieldRest10'
        displayNameFieldId:
          type: string
          description: For your custom object record to have a meaningful name field, you must create a custom object field which will act as a name. You can then use the desired custom object field's id as the value for this parameter.
        uniqueCodeFieldId:
          type: string
          description: For your custom object record to have a unique identifier, you must create a custom object field which will act as a GUID. You can then use the desired custom object field's id as the value for this parameter.
        deleteLinkedCustomObjectData:
          type: string
          description: Whether or not custom object records are deleted when linked contact records are deleted. Does not apply to records that are unmapped or account deletion. Deleting records is irreversible and data cannot be recovered. The default value is <code>false</code>. This feature is released under our Controlled Availability program. You can request access to this feature by submitting a request to <a href='https://support.oracle.com/epmos/faces/MosIndex.jspx'>My Oracle Support</a>.
    CustomObjectFieldRest10:
      title: CustomObjectField
      properties:
        type:
          type: string
          description: 'The asset''s type in Eloqua. This is a read-only property. '
        id:
          type: string
          readOnly: true
          description: Id of the custom object field. This is a read-only property. Use negative ids to reference custom object fields for other properties (e.g. emailAddressFieldId or uniqueCodeFieldId). See example.
        currentStatus:
          type: string
          description: This property is not used for custom objects.
        description:
          type: string
          description: This property is not used for custom object fields.
        permissions:
          type: string
          description: This property is not used.
        createdBy:
          type: string
          readOnly: true
          description: This property is not used for custom object fields.
        createdAt:
          type: string
          readOnly: true
          description: This property is not used for custom object fields.
        updatedBy:
          type: string
          readOnly: true
          description: This property is not used for custom object fields.
        updatedAt:
          type: string
          readOnly: true
          description: This property is not used for custom object fields.
        depth:
          type: string
          readOnly: true
          description: 'Level of detail returned by the request. Eloqua APIs can retrieve entities at three different levels of depth: <code>minimal</code>, <code>partial</code>, and <code>complete</code>. Any other values passed are reset to <code>complete</code> by default. For more information, see <a href=''https://docs.oracle.com/cloud/latest/marketingcs_gs/OMCAB/index.html#CSHID=RequestDepth''>Request depth</a>.'
        name:
          type: string
          description: The name of the custom object field.
        displayType:
          type: string
          description: The custom object field's display type.
        dataType:
          type: string
          description: The custom object field's data type.
        defaultValue:
          type: string
          description: The custom object field's default value.
